server:
  port: ${PORT:8081}
spring:
  application:
    name: business-app
  jpa:
    database: MYSQL
    properties:
      hibernate:
        show_sql: true
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://${MYSQL_HOST:localhost}:${MYSQL_PORT:3306}/${MYSQL_DATABASE:simple_web_app}
    username: ${MYSQL_USERNAME:root}
    password: ${MYSQL_PASSWORD:root}
  liquibase:
    change-log: classpath:/db/changelog/db.changelog-master.yaml
